QuanLyDoanVien/QuanLyDoanVien.UI/Controllers/ThayDoiMatKhauController.cs
using QuanLyDoanVien.DAL;
using QuanLyDoanVien.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyDoanVien.UI.Controllers
{
    public class ThayDoiMatKhauController : Controller
    {
        // GET: ThayDoiMatKhau
        public ActionResult ThongTinTaiKhoan()
        {
            TaiKhoanSinhVienDAL sv = new TaiKhoanSinhVienDAL();
            ModelState.Clear();
            return View(sv.TaiKhoanSV("15110171"));
        }

        // GET: ThayDoiMatKhau/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ThayDoiMatKhau/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ThayDoiMatKhau/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ThayDoiMatKhau/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        // POST: ThayDoiMatKhau/Edit/5
        [HttpPost]
        public ActionResult DoiMatKhau(TaiKhoanSinhVienModel sv)
        {
            try
            {
                TaiKhoanSinhVienDAL tk = new TaiKhoanSinhVienDAL();
                if (tk.DoiMatKhau(sv))
                {
                    ViewBag.ErrorMessage = "Cập Nhật Thành Công";
                }
                else
                {
                    ViewBag.ErrorMessage = "Cập Nhật Không Thành Công";
                }
            }catch(Exception e)
            {
                ViewBag.ErrorMessage = "Cập Nhật Không Thành Công";
            }
            return View("ThongTinTaiKhoan");
        }

        // GET: ThayDoiMatKhau/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ThayDoiMatKhau/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

QuanLyDoanVien/QuanLyDoanVien.UI/Views/ThayDoiMatKhau/ThongTinTaiKhoan.cshtml
@model QuanLyDoanVien.Models.TaiKhoanSinhVienModel

@{
    ViewBag.Title = "ThongTinTaiKhoan";
    Layout = "~/Views/Shared/_LayoutStudent.cshtml";
}

@if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.ErrorMessage
    </div>
}





<div class="row">
    <div class="col-md-12">
        <div class="portlet box red-sunglo">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i>Thông Tin Tài Khoản
                </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse">
                    </a>
                    <a href="javascript:;" class="reload">
                    </a>
                </div>
            </div>
            <div class="portlet-body form">
                <!-- BEGIN FORM-->
                @using (Html.BeginForm("DoiMatKhau", "ThayDoiMatKhau", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal form-bordered" }))
                 {
                    <div class="form-body">
                        <div class="form-group">
                            <label class="control-label col-md-3">Tên Đăng Nhập</label>
                            <div class="col-md-9">
                                @Html.TextBoxFor(model => model.TenDangNhap, new { @class = "form-control", @readonly="readonly", @type="text" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3">Mật Khẩu</label>
                            <div class="col-md-9">
                                @Html.TextBoxFor(model => model.MatKhauCu, new { @class = "form-control", @type = "password" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3">Mật Khẩu Mới</label>
                            <div class="col-md-9">
                                @Html.TextBoxFor(model => model.MatKhauMoi, new { @class = "form-control", @type = "password" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3">Xác Nhận Mật Khẩu</label>
                            <div class="col-md-9">
                                @Html.TextBoxFor(model => model.XacNhanMatKhau, new { @class = "form-control", @type = "password" })
                            </div>
                        </div>
                    </div>
                    <div class="margin-top-10" style="text-align: center; margin-top: 50px !important; padding-bottom: 20px !important;">
                        <input type="submit" class="btn green-haze" />
                    </div>
                }
                <!-- END FORM-->
            </div>
        </div>
    </div>
</div>